apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 32333
    nodePort: 32333
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
